# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: M2Team.NanaZip
PackageVersion: 3.0.1000.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- nanazip
FileExtensions:
- 7z
- ar
- arj
- bzip2
- cab
- chm
- cpio
- cramfs
- dmg
- ext
- fat
- gpt
- gzip
- hfs
- ihex
- iso
- lzh
- lzma
- mbr
- msi
- nsis
- ntfs
- qcow2
- rar
- rpm
- squashfs
- tar
- udf
- uefi
- vdi
- vhd
- vmdk
- wim
- xar
- xz
- z
- zip
PackageFamilyName: 40174MouriNaruto.NanaZip_gnj4mf6z9tkrc
ReleaseDate: 2024-05-27
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/3.0.1000.0/NanaZip_3.0.1000.0.msixbundle
  InstallerSha256: 27D4EAD5F9AF51E573145CE1CCA78F063606AB8AE8F7124801D4D887453F5397
  SignatureSha256: 632B5C4F6A758BED7ABE698217E14294D4D00DF848FAD9070EC6D2F26E50C2DA
- Architecture: x64
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/3.0.1000.0/NanaZip_3.0.1000.0.msixbundle
  InstallerSha256: 27D4EAD5F9AF51E573145CE1CCA78F063606AB8AE8F7124801D4D887453F5397
  SignatureSha256: 632B5C4F6A758BED7ABE698217E14294D4D00DF848FAD9070EC6D2F26E50C2DA
- Architecture: arm64
  InstallerUrl: https://github.com/M2Team/NanaZip/releases/download/3.0.1000.0/NanaZip_3.0.1000.0.msixbundle
  InstallerSha256: 27D4EAD5F9AF51E573145CE1CCA78F063606AB8AE8F7124801D4D887453F5397
  SignatureSha256: 632B5C4F6A758BED7ABE698217E14294D4D00DF848FAD9070EC6D2F26E50C2DA
ManifestType: installer
ManifestVersion: 1.6.0
