# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: RustDesk.RustDesk.Nightly
PackageVersion: 1.2.5
PackageLocale: en-US
Publisher: RustDesk
PublisherUrl: https://github.com/rustdesk
PublisherSupportUrl: https://github.com/rustdesk/rustdesk/issues
PackageName: RustDesk Nightly
PackageUrl: https://github.com/rustdesk/rustdesk
License: AGPL-3.0
LicenseUrl: https://github.com/rustdesk/rustdesk/blob/master/LICENCE
ShortDescription: An open-source remote desktop software, works out of the box, no configuration required, written in Rust.
Tags:
- anydesk
- dart
- flutter
- flutter-apps
- flutter-desktop
- flutter-examples
- flutter-mobile
- flutter-ui
- flutter-web
- p2p
- rdp
- remote-control
- remote-desktop
- rust
- teamviewer
- vnc
ReleaseNotes: |-
  This is a pre-release, welcome to test
  image| Architecture | Windows | Ubuntu | Mac | Android | Flatpak | AppImage |
  |--------------|---------|--------|-----|----------|---------|---------|
  | x86-64 (64-bit) | EXE   MSI | Download | Download |  | Download | Download |
  | AArch64 (ARM64) |  | Download | Download | Download | Download |  Download  |
  | ARMv7 (32-bit) |  | Download |  |  Download |  |  |
  | x86-32 (32-bit) | Download |  |  |  |  |  |For more downloads (Fedora / Arch Linux / Suse): check below please
  For the latest features: check out the nightly build
ReleaseNotesUrl: https://github.com/rustdesk/rustdesk/releases/tag/1.2.5
ManifestType: defaultLocale
ManifestVersion: 1.6.0
