# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LoginSecurite.Lsassy
PackageVersion: 3.1.11
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lsassy.exe
UpgradeBehavior: install
Commands:
- lsassy
ReleaseDate: 2024-05-13
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/login-securite/lsassy/releases/download/v3.1.11/lsassy-windows-latest.zip
  InstallerSha256: 6F3EF66224C736A1B740D4DCFD404D2C6EA07735034E1FE0CBC9A3C13B37D5D2
ManifestType: installer
ManifestVersion: 1.6.0
