# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Ionuttbara.WindowsDefenderRemover
PackageVersion: 12.8.0
PackageLocale: en-US
Publisher: Gallery Inc
PublisherUrl: https://github.com/ionuttbara
Author: Ionuț Bara
PackageName: Defender Remover
PackageUrl: https://github.com/ionuttbara/windows-defender-remover
License: CC BY-NC 4.0
LicenseUrl: https://github.com/ionuttbara/windows-defender-remover/blob/main/LICENSE
Copyright: Gallery Inc.
ShortDescription: A tool which is used to remove Windows Defender in Windows 8.x, Windows 10 (every version) and Windows 11.
Description: This application removes / disables Windows Defender, including the Windows Security App, Windows Virtualization-Based Security (VBS), Windows SmartScreen, Windows Security Services, Windows Web-Threat Service, Windows File Virtualization (UAC), Microsoft Defender App Guard, Microsoft Driver Block List, System Mitigations and the Windows Defender page in the Settings App on Windows 10 or later.
Tags:
- defender
- defender-disabler
- defender-remover
- security
- tweaking
- windows
- windows-defender
ReleaseNotesUrl: https://github.com/ionuttbara/windows-defender-remover/releases/tag/release_def_12_8
ManifestType: defaultLocale
ManifestVersion: 1.6.0
